#!/usr/bin/env python3
"""Expand authored regional dossiers into a linked first-draft encyclopedia.

Central incidents and article premises are authored in dossiers.json. The
recurrent passages state each region's shared history and the practical
implications of the article's role. They are deliberately identified as
context in the rendered source records, rather than presented as quotations.
"""
import json, pathlib, re

ROOT=pathlib.Path(__file__).resolve().parents[1]
KINDS=['Person','Place','Institution','Event','Artifact','Custom','Text','Creature','Route','Law',
       'Person','Place','Institution','Event','Artifact','Custom','Text','Phenomenon','Trade','Dispute']

REGIONS={
'Vey': 'Vey households measure wealth partly in dependable access to a public landing. Their markets exchange grain, lamp oil, glazed jars, and legal testimony. A witness can authenticate a transaction but cannot provide the labor needed to fulfill it. Seasonal crews clean the same embankments on which courts announce judgments, and a decision that ignores those crews soon meets an expensive physical limit. Flood deposits preserve small objects while destroying the arrangement that once made their meaning obvious. Recovering an object is therefore easier than establishing what anybody was entitled to do with it.',
'Orun': 'The Orun channels shift across a landscape whose legal descriptions often name vanished banks. Fishers, reed workers, and gardeners share access without sharing a single account of ownership. Transport depends on shallow boats and pilots who read changes in sediment. Salt reaches some plots well before neighboring plots, making an apparently equal assessment unfair in practice. An ancestral claim can survive a change in the channel, but its observance may become impossible at the old site. Communities must decide whether to move the observance, compensate its claimants, or leave the affected water unused.',
'Keth': 'Keth communities inhabit chalk shelves where rainfall must be collected before it drains into inaccessible fissures. Builders maintain cistern roofs, plastered channels, and terraces with tools that families repair for generations. Burial niches compete with storage rooms for dry space. Ordinary seepage can resemble ancestral interference, so reliable testimony begins with inspecting masonry and comparing neighboring water levels. The most powerful household is seldom able to sustain a settlement alone. It depends on masons, charcoal carriers, and shepherds whose labor does not appear in the grand genealogies carved above the cistern doors.',
'Talassar': 'Talassar combines salt marshes, sheltered boat towns, and orchards whose irrigation depends on tidal timing. Merchants trade durable claims alongside perishable cargo, although only an actual witnessed undertaking has force after death. A repaired boat, a borrowed name, and a neglected drain can each determine whether a contract remains practical. Houses that prosper from distant obligations are exposed to local maintenance costs they would prefer to call somebody else’s problem. Seasonal kitchens and landing crews keep accounts that often describe the region more accurately than its ceremonial histories of uninterrupted family success.',
'Namar': 'The Namar passes join pasture settlements to caravan markets. Pack animals carry nearly everything that cannot be made from local stone, wool, or timber. Snow closes crossings irregularly, and a route that is short on a map may cost more food than a longer sheltered path. Hospices preserve undertakings made by travelers who never returned. Their custodians cannot assume that a visitor belongs to one sovereign or one witness tradition. A workable agreement must specify which season, which spring, and which people it protects, rather than claiming a universal welcome the stores cannot support.',
'Istren': 'Istren’s fishing villages and timber monasteries occupy a rainy coast where repairing roofs is a continuing expense rather than a finished achievement. Boats make neighboring settlements accessible when inland tracks become mud. Smokehouses, net yards, and communal ovens provide the places where people exchange reliable news. The dead are remembered through finite promises attached to landing water and particular working seasons. A claim on an abandoned beach can become dangerous when erosion moves a new household into its reach. Islanders generally test an alleged manifestation against wind, rot, and tides before paying for an interpreter.',
'Suth': 'The Suth valleys cultivate grafted orchards and irrigated gardens amid dry hills. Food production depends on precise local knowledge: when to open a channel, which rootstock tolerates mineral water, and how many hands a harvest requires. Asylum customs let strangers work under temporary names, but temporary recognition does not automatically convey inheritance. The same gardens can preserve an old promise and expose its injustice. A court that assigns water without accounting for the labor of keeping it clean may issue a valid judgment that no household can afford to obey.',
'Avel': 'Avel’s islands preserve competing versions of the basin’s earliest treaties. Sea crossings depend on sails, weather, and provisions, giving a copied text little authority unless somebody can carry its terms home and explain them. Fishing households share beaches with custodians of drowned foundations. Low water reveals masonry that changes both navigation and historical argument. An island’s isolation can shelter dissent and conceal abuse; its effects depend upon who controls the boats. Agreements are usually bounded by named landing places, because a promise to protect an entire sea would have no workable observance.'
}

ROLE={
'Person': 'Later accounts make {name} the explanation for an entire local change. The surviving record instead places this life among dependencies: an introduction supplied by another household, materials purchased on credit, and testimony given by people with reasons of their own. A biography that removes those dependencies becomes a useful legend and a poor guide to what happened. Descendants inherit evidence and expectations, rather than the ability to repeat an ancestor’s achievement. The practical question is which part of the achievement can be maintained by ordinary people after the celebrated individual is gone.',
'Place': 'The site has changed use more than once. Its surviving structures should not be read as a single intact design: one household repairs what another abandoned, and a later occupant can preserve a wall while giving its opening a different purpose. Visitors who search only for the original foundation overlook the people paying for the present roof. Custody depends on continuing access and maintenance, not merely on a persuasive genealogy. Removing an interesting object may erase evidence of a repair that explains why the place remains habitable at all.',
'Institution': 'The institution’s public account emphasizes its founding purpose, while daily accounts reveal exceptions, unpaid work, and compromises with neighbors. Membership does not imply agreement. A clerk, a patron, and a laborer can defend the same arrangement for incompatible reasons. Its authority is strongest where it provides something people actually need and weakest where it claims that need as proof of permanent jurisdiction. Reform requires deciding who will perform the useful work afterward. Simply abolishing the name may leave the obligation in the hands of less accountable successors.',
'Event': 'The event survives through records made for different purposes. A household remembers hunger; a court records jurisdiction; a custodian records the interruption of an observance. Their dates can be reconciled without making their explanations identical. Later commemorations often select a decisive moment because a ceremony needs a beginning and an end. The consequences were less orderly, traveling through marriages, prices, and people who moved away. An honest account follows those consequences far enough to distinguish a temporary outcome from an agreement that still constrains the present.',
'Artifact': 'Material inspection places limits on the object’s legend. Repairs, wear, and changes in custody can establish that it was used repeatedly without proving every story attached to it. Its value is relational: somebody can authenticate it, somebody needs it for an observance, and somebody may suffer if it is removed. An expensive replacement would not automatically inherit those relations. Custodians therefore record loans and repairs as carefully as ceremonial appearances. A collector who purchases the object but ignores its attached undertaking may own something that cannot safely be taken home.',
'Custom': 'The custom is learned through participation rather than a single authoritative text. Households disagree about details while recognizing enough shared actions to cooperate. That flexibility can admit newcomers or allow influential families to redefine the practice in their own favor. Describing it as ancient settles neither possibility. Its practical test is whether a participant can question a demand without losing access to food, water, or witnesses. Local reformers seek finite observances whose costs can be recorded, so that reverence for predecessors does not become an unanswerable demand upon children.',
'Text': 'Copies disagree in ways that matter. A shortened phrase can remove a condition, and a copied date can imply that a later amendment belonged to the original undertaking. Dry writing preserves evidence but cannot make an oath binding by itself. Readers must distinguish a record of consent from a writer’s assertion that consent occurred. Marginal notes are sometimes the only surviving testimony of people excluded from the formal version. Establishing a trustworthy reading therefore depends on comparing custody, material, and ordinary expenses, as well as elegant arguments about wording.',
'Creature': 'Reports describe a living creature before they describe a supernatural emblem. It needs food, shelter, and a place to breed, and it reacts to disturbances that witnesses may misunderstand. A keeper who recognizes those needs can often prevent the encounter later remembered as a curse. The animal cannot be made into an obedient instrument of ancestral power. Where an undertaking changes its habitat, the effect is indirect and costly to other inhabitants. Stories that treat its behavior as a moral verdict obscure both ordinary suffering and the human decisions that altered the site.',
'Route': 'A route is an agreement between people maintaining its difficult portions, as much as a line across terrain. Tolls buy repairs only when their recipients are accountable for the work. A passage described as open may still be unusable for children, loaded animals, or travelers without an accepted witness. Seasonal detours preserve movement while distributing its costs to other households. Pilots and guides keep alternative accounts of distance because time, provisions, and exposure matter more than ceremonial measures. Closing one stretch can therefore revise obligations far beyond its immediate neighborhood.',
'Law': 'The rule’s force depends on a stated scope. It governs named acts and claimants, rather than every future disagreement that resembles its original case. Courts have nevertheless tried to extend it, usually when a narrow precedent would benefit a powerful applicant. Opponents do not have to deny ancestor law to challenge that extension. They can ask which promise was actually made, who witnessed it, and whether the required observance remains possible. The difference between a valid undertaking and a convenient assertion of authority is central to the current dispute.',
'Phenomenon': 'Witnesses distinguish an observed effect from their explanation for it. Repetition under comparable conditions is valuable evidence; a striking story told after its alleged cause becomes famous is weaker evidence. Masons, gardeners, and boat crews often recognize patterns an interpreter overlooks. Their explanation may reduce the immediate danger without settling whether an undertaking contributed to it. The basin has no institution capable of issuing a final answer for every manifestation. Communities record the conditions under which the effect occurs, then negotiate a response whose costs they can actually sustain.',
'Trade': 'The trade depends upon tools, training, reliable materials, and people who perform work its public account barely mentions. A skilled craftsperson can improve a process, yet every batch still requires hands and a season of available materials. Output remains bounded by fuel, animals, weather, and the hands available to repair equipment. Prices carry the history of these constraints into households far from the workshop. A commercial undertaking that survives its maker can preserve useful cooperation or prevent successors from adapting to changed conditions. The present negotiation concerns how to retain knowledge while releasing an obligation nobody can now perform.',
'Dispute': 'The dispute contains more than two positions. People with the same formal entitlement may face different practical costs, while opponents can depend upon the same canal, kitchen, or crossing. A complete settlement must describe an executable change rather than award a satisfying phrase to one side. Evidence about a past wrong remains necessary even when compensation cannot restore the original arrangement. Local negotiators separate immediate maintenance from the final assessment of responsibility. This allows a place to remain usable while its inhabitants continue an argument they have good reason not to abandon.'
}

def slug(s):return re.sub(r'[^a-z0-9]+','-',s.lower()).strip('-')

def main():
    dossiers=[json.loads(p.read_text()) for p in sorted((ROOT/'lore'/'dossiers').glob('*.json'))]
    for d in dossiers:
        batch=d['batch']; entries=[]
        rows=d['rows']; ids=[f"b{batch:03d}-"+slug(r[0]) for r in rows]
        for n,(title,seed) in enumerate(rows):
            kind=KINDS[n]; first=rows[0][0]; law=rows[9][0]
            name=title
            links=[ids[(n-1)%20],ids[(n+1)%20],ids[(n+7)%20]]
            if batch==2:links.append('the-public-kitchen-witnesses')
            else:
                prev=next(x for x in dossiers if x['batch']==batch-1)
                links.append(f"b{batch-1:03d}-"+slug(prev['rows'][9][0]))
            if any(x['batch']==batch+1 for x in dossiers):
                nex=next(x for x in dossiers if x['batch']==batch+1)
                links.append(f"b{batch+1:03d}-"+slug(nex['rows'][0][0]))
            # Each seed is a separately authored premise and immediate consequence.
            body=seed+'\n\n'+ROLE[kind].format(name=name)
            body+=f"\n\nThis belongs to {d['title']}. {d['history']}"
            background=REGIONS[d['region']]
            body+=f"\n\nIn the connected record, [{rows[(n+1)%20][0]}]({ids[(n+1)%20]}.md) preserves another part of this history. The terms recorded under [{law}]({ids[9]}.md) delimit the local obligation; they do not grant a ruler unlimited command over the dead. The unresolved issue in 1248 is concrete: {d['question']}"
            entries.append({'id':ids[n],'title':title,'kind':kind,'region':d['region'],
              'date':f"{d['year']}–1248",'body':body,'background':background,'links':links,
              'inspiration':'One of the shared cycle’s source transformations: '+d['transformations'][n%4]+' The batch notes distinguish all four transformations; this article develops the combined fictional history.'})
        cycle={'batch':batch,'title':d['title'],'summary':d['summary'],
               'source_notes':d['transformations'],'entries':entries,'draft_method':'Authored premises with shared regional context and role analysis; editorial first draft.'}
        (ROOT/'lore'/'cycles'/f'{batch:03d}.json').write_text(json.dumps(cycle,ensure_ascii=False,indent=2))

if __name__=='__main__':main()
